package main

import (
	"html/template"
	"time"
)

func init() {
	actions = []action{
		{ID: "status", Label: "Статус Xray Go", Description: "Единый статус failover, watchdog и восстановления", Command: []string{"/opt/bin/xray-go", "status"}, Timeout: 20 * time.Second, Group: "overview", Tone: "primary"},
		{ID: "doctor", Label: "Диагностика для поддержки", Description: "Безопасная диагностика для отправки в поддержку", Command: []string{"/opt/bin/xray-go", "doctor", "--support"}, Timeout: 150 * time.Second, Group: "diagnostics", Tone: "primary"},
		{ID: "switch-primary", Label: "Переключить на основной", Description: "Активировать основной профиль", Command: []string{"/opt/bin/xray-go", "switch", "primary"}, Timeout: 90 * time.Second, Group: "failover", Tone: "purple"},
		{ID: "switch-backup", Label: "Переключить на резервный", Description: "Активировать резервный профиль", Command: []string{"/opt/bin/xray-go", "switch", "backup"}, Timeout: 90 * time.Second, Group: "failover", Tone: "amber"},
		{ID: "update-active", Label: "Обновить активный конфиг", Description: "Перегенерировать активный конфиг Xray", Command: []string{"/opt/bin/vless-go-failover", "update-active"}, Timeout: 120 * time.Second, Group: "updates", Tone: "cyan"},
		{ID: "auto-update-run", Label: "Запустить автообновление", Description: "Запустить обновление подписок сейчас", Command: []string{"/opt/bin/vless-go-auto-update", "run"}, Timeout: 150 * time.Second, Group: "updates", Tone: "cyan"},
		{ID: "update-go", Label: "Обновить Go edition", Description: "Обновить xray-go helpers и Go edition", Command: []string{"/opt/bin/xray-go", "update"}, Timeout: 300 * time.Second, Group: "updates", Tone: "cyan"},
		{ID: "update-core", Label: "Обновить Xray-core", Description: "Обновить Xray-core через безопасный updater", Command: []string{"/opt/bin/xray-go", "update-core"}, Timeout: 360 * time.Second, Group: "updates", Tone: "danger"},
		{ID: "recover-status", Label: "Статус восстановления", Description: "Показать статус тихой ежечасной проверки", Command: []string{"/opt/bin/xray-go", "recover", "status"}, Timeout: 30 * time.Second, Group: "recovery", Tone: "secondary"},
		{ID: "recover-check", Label: "Проверить здоровье", Description: "Проверить состояние без recovery-действий", Command: []string{"/opt/bin/xray-go", "recover", "check"}, Timeout: 45 * time.Second, Group: "recovery", Tone: "secondary"},
		{ID: "recover-run", Label: "Восстановить сейчас", Description: "Запустить цепочку самовосстановления", Command: []string{"/opt/bin/xray-go", "recover"}, Timeout: 180 * time.Second, Group: "recovery", Tone: "amber"},
		{ID: "recover-enable", Label: "Включить ежечасно", Description: "Включить ежечасную тихую проверку", Command: []string{"/opt/bin/xray-go", "recover", "enable-hourly"}, Timeout: 45 * time.Second, Group: "recovery", Tone: "cyan"},
		{ID: "recover-disable", Label: "Отключить ежечасно", Description: "Отключить ежечасную recovery-проверку", Command: []string{"/opt/bin/xray-go", "recover", "disable-hourly"}, Timeout: 45 * time.Second, Group: "recovery", Tone: "secondary"},
		{ID: "restart-xray", Label: "Перезапустить Xray", Description: "Перезапустить сервис Xray", Command: []string{"/opt/etc/init.d/S24xray", "restart"}, Timeout: 45 * time.Second, Group: "maintenance", Tone: "secondary"},
		{ID: "restart-watchdog", Label: "Перезапустить watchdog", Description: "Перезапустить сервис watchdog", Command: []string{"/opt/etc/init.d/S26vless-go-watchdog", "restart"}, Timeout: 45 * time.Second, Group: "maintenance", Tone: "secondary"},
		{ID: "cleanup-dry-run", Label: "Проверить очистку", Description: "Предпросмотр безопасной очистки", Command: []string{"/opt/bin/vless-go-cleanup", "--dry-run"}, Timeout: 45 * time.Second, Group: "maintenance", Tone: "secondary"},
		{ID: "history", Label: "История", Description: "История переключений", Command: []string{"/opt/bin/xray-go", "history"}, Timeout: 30 * time.Second, Group: "logs", Tone: "secondary"},
		{ID: "recovery-log", Label: "Лог восстановления", Description: "Последние строки recovery log", Command: []string{"/bin/sh", "-c", "tail -n 100 /opt/var/log/vless-go-recover.log 2>/dev/null || true"}, Timeout: 30 * time.Second, Group: "logs", Tone: "secondary"},
		{ID: "watchdog-log", Label: "Лог watchdog", Description: "Последние строки watchdog log", Command: []string{"/bin/sh", "-c", "tail -n 100 /opt/var/log/vless-go-watchdog.log 2>/dev/null || true"}, Timeout: 30 * time.Second, Group: "logs", Tone: "secondary"},
	}

	page = template.Must(template.New("page").Funcs(template.FuncMap{"actionsIn": actionsIn}).Parse(russianPageHTML))
}

const russianPageHTML = `<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Xray Go Control</title>
<style>
:root{--bg:#08090c;--panel:#15171c;--line:#343844;--text:#f7f7f8;--muted:#a4acb8;--blue:#2563eb;--cyan:#0891b2;--green:#16a34a;--amber:#d97706;--red:#b91c1c;--purple:#7c3aed}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.content{max-width:1280px;margin:0 auto;padding:24px}.top{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;background:#101116;border:1px solid var(--line);border-radius:22px;padding:22px;margin-bottom:18px}h1{font-size:34px;margin:0 0 8px}h2{margin:0 0 14px;font-size:21px}.muted,.listen,.note,.desc{color:var(--muted)}.listen{font-size:13px;margin-top:8px}.badge{display:inline-flex;gap:8px;align-items:center;border-radius:999px;padding:10px 14px;font-weight:800;white-space:nowrap;border:1px solid #14532d;background:#052e16;color:#bbf7d0}.dot{width:9px;height:9px;border-radius:999px;background:#22c55e;box-shadow:0 0 16px #22c55e}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px;margin-bottom:18px}.card{background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:17px;min-height:102px;position:relative;overflow:hidden}.card:before{content:"";position:absolute;left:0;top:17px;bottom:17px;width:6px;border-radius:8px;background:var(--accent,var(--blue))}.label{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);margin-left:13px}.value{font-size:24px;font-weight:850;margin:12px 0 0 13px;white-space:pre-line}.grid{display:grid;grid-template-columns:1.05fr .95fr;gap:18px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:18px;margin-bottom:18px}.kicker{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);margin-bottom:8px}.actions{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}button{width:100%;padding:12px 14px;border:0;border-radius:11px;background:#3f3f46;color:white;font-weight:800;cursor:pointer}.primary button{background:var(--blue)}.cyan button{background:var(--cyan)}.purple button{background:var(--purple)}.amber button{background:var(--amber)}.danger button{background:var(--red)}button:hover{filter:brightness(1.08)}.desc{font-size:12px;line-height:1.35;margin-top:7px}pre{white-space:pre-wrap;word-break:break-word;background:#050506;border:1px solid var(--line);border-radius:14px;padding:15px;max-height:620px;overflow:auto;color:#d6d9df}.formgrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}label{display:block;color:#d9dde5;font-size:13px;font-weight:800}input,select{width:100%;margin:7px 0 12px;padding:11px 12px;border-radius:10px;border:1px solid #525866;background:#08090c;color:#f7f7f8}.note{font-size:12px;line-height:1.5}@media(max-width:920px){.content{padding:16px}.top{display:block}.badge{margin-top:15px}.grid{grid-template-columns:1fr}}
</style></head><body><main class="content">
<section class="top"><div><h1>Xray Go Control</h1><div class="muted">Панель управления Keenetic Xray Installer: Full Go / Entware, failover, watchdog и восстановление.</div><div class="listen">Адрес: {{.Listen}}</div></div><div class="badge"><span class="dot"></span>{{.Health}}</div></section>
<section class="cards"><div class="card" style="--accent:var(--green)"><div class="label">Активный слот</div><div class="value">{{.Active}}</div></div><div class="card" style="--accent:var(--cyan)"><div class="label">Основной</div><div class="value">{{.Primary}}</div></div><div class="card" style="--accent:var(--purple)"><div class="label">Резервный</div><div class="value">{{.Backup}}</div></div><div class="card" style="--accent:var(--amber)"><div class="label">Watchdog</div><div class="value">{{.Watchdog}}</div></div><div class="card" style="--accent:var(--blue)"><div class="label">Восстановление</div><div class="value">{{.Recovery}}</div></div><div class="card" style="--accent:var(--cyan)"><div class="label">Proxy0</div><div class="value">{{.Proxy0}}</div></div></section>
<div class="grid"><div><section class="panel"><div class="kicker">Обзор</div><h2>Статус и диагностика</h2><div class="actions">{{range actionsIn .Actions "overview"}}<form method="post" action="/action" class="{{.Tone}}"><input type="hidden" name="token" value="{{$.Token}}"><input type="hidden" name="id" value="{{.ID}}"><button>{{.Label}}</button><div class="desc">{{.Description}}</div></form>{{end}}{{range actionsIn .Actions "diagnostics"}}<form method="post" action="/action" class="{{.Tone}}"><input type="hidden" name="token" value="{{$.Token}}"><input type="hidden" name="id" value="{{.ID}}"><button>{{.Label}}</button><div class="desc">{{.Description}}</div></form>{{end}}</div></section>
<section class="panel"><div class="kicker">Переключение</div><h2>Основной / резервный</h2><div class="actions">{{range actionsIn .Actions "failover"}}<form method="post" action="/action" class="{{.Tone}}"><input type="hidden" name="token" value="{{$.Token}}"><input type="hidden" name="id" value="{{.ID}}"><button>{{.Label}}</button><div class="desc">{{.Description}}</div></form>{{end}}</div></section>
<section class="panel"><div class="kicker">Восстановление</div><h2>Тихая проверка и self-healing</h2><div class="actions">{{range actionsIn .Actions "recovery"}}<form method="post" action="/action" class="{{.Tone}}"><input type="hidden" name="token" value="{{$.Token}}"><input type="hidden" name="id" value="{{.ID}}"><button>{{.Label}}</button><div class="desc">{{.Description}}</div></form>{{end}}</div></section>
<section class="panel"><div class="kicker">Источники</div><h2>Источники и selectors</h2><form method="post" action="/set-source"><input type="hidden" name="token" value="{{.Token}}"><div class="formgrid"><div><label>Слот</label><select name="slot"><option value="primary">основной / primary</option><option value="backup">резервный / backup</option></select></div><div><label>Выбор профиля</label><input name="selector" value="first" placeholder="first, index:7 или name"></div></div><label>Источник или URL подписки</label><input type="password" name="source" autocomplete="off" placeholder="Вставь ссылку или URL подписки"><button>Сохранить источник</button></form><p class="note">Значения источников отправляются как password-поля и не выводятся обратно на страницу.</p><form method="post" action="/set-selector"><input type="hidden" name="token" value="{{.Token}}"><div class="formgrid"><div><label>Selector основного</label><input name="primary" value="{{.PrimarySel}}"></div><div><label>Selector резервного</label><input name="backup" value="{{.BackupSel}}"></div></div><button>Сохранить selectors</button></form></section></div>
<div><section class="panel"><div class="kicker">Статус</div><h2>Системный статус</h2><pre>{{.Status}}</pre></section><section class="panel"><div class="kicker">Обновления</div><h2>Обновления</h2><div class="actions">{{range actionsIn .Actions "updates"}}<form method="post" action="/action" class="{{.Tone}}"><input type="hidden" name="token" value="{{$.Token}}"><input type="hidden" name="id" value="{{.ID}}"><button>{{.Label}}</button><div class="desc">{{.Description}}</div></form>{{end}}</div></section><section class="panel"><div class="kicker">Обслуживание</div><h2>Обслуживание</h2><div class="actions">{{range actionsIn .Actions "maintenance"}}<form method="post" action="/action" class="{{.Tone}}"><input type="hidden" name="token" value="{{$.Token}}"><input type="hidden" name="id" value="{{.ID}}"><button>{{.Label}}</button><div class="desc">{{.Description}}</div></form>{{end}}</div></section><section class="panel"><div class="kicker">Логи</div><h2>Логи и история</h2><div class="actions">{{range actionsIn .Actions "logs"}}<form method="post" action="/action" class="{{.Tone}}"><input type="hidden" name="token" value="{{$.Token}}"><input type="hidden" name="id" value="{{.ID}}"><button>{{.Label}}</button><div class="desc">{{.Description}}</div></form>{{end}}</div></section></div></div>
{{if .Output}}<section class="panel"><div class="kicker">Вывод</div><h2>Вывод команды</h2><pre>{{.Output}}</pre></section>{{end}}<section class="panel"><div class="kicker">Безопасность</div><h2>Только локальная сеть</h2><p class="note">Используй Web UI только в доверенной локальной сети. Не публикуй порт Web UI в интернет/WAN. Диагностика для поддержки запускается через <code>xray-go doctor --support</code>.</p></section></main></body></html>`
