package main

import "time"

// init aligns the optional Web UI actions with the v0.1.4 xray-go/recovery workflow.
//
// This intentionally avoids changing the large embedded HTML template in main.go.
// The existing template already renders action groups. Here we only replace the
// action list with safer high-level entrypoints and recovery controls.
func init() {
	actions = []action{
		{
			ID:          "status",
			Label:       "Xray Go status",
			Description: "Единый статус: failover, watchdog и recovery",
			Command:     []string{"/opt/bin/xray-go", "status"},
			Timeout:     15 * time.Second,
			Group:       "overview",
			Tone:        "primary",
		},
		{
			ID:          "watchdog-status",
			Label:       "Статус watchdog",
			Description: "Показать статус daemon watchdog",
			Command:     []string{"/opt/bin/vless-go-watchdog", "status"},
			Timeout:     10 * time.Second,
			Group:       "overview",
			Tone:        "secondary",
		},
		{
			ID:          "doctor-support",
			Label:       "Doctor support",
			Description: "Безопасная диагностика без raw VLESS/subscription данных",
			Command:     []string{"/opt/bin/xray-go", "doctor", "--support"},
			Timeout:     120 * time.Second,
			Group:       "diagnostics",
			Tone:        "primary",
		},
		{
			ID:          "switch-primary",
			Label:       "Переключить на основной",
			Description: "Активировать primary source через xray-go",
			Command:     []string{"/opt/bin/xray-go", "switch", "primary"},
			Timeout:     60 * time.Second,
			Group:       "failover",
			Tone:        "purple",
		},
		{
			ID:          "switch-backup",
			Label:       "Переключить на резервный",
			Description: "Активировать backup source через xray-go",
			Command:     []string{"/opt/bin/xray-go", "switch", "backup"},
			Timeout:     60 * time.Second,
			Group:       "failover",
			Tone:        "amber",
		},
		{
			ID:          "update-active",
			Label:       "Обновить активный конфиг",
			Description: "Перегенерировать активный Xray config",
			Command:     []string{"/opt/bin/vless-go-failover", "update-active"},
			Timeout:     90 * time.Second,
			Group:       "sources",
			Tone:        "cyan",
		},
		{
			ID:          "update-go-edition",
			Label:       "Update Go edition",
			Description: "Обновить xray-go helpers и Full Go edition",
			Command:     []string{"/opt/bin/xray-go", "update"},
			Timeout:     240 * time.Second,
			Group:       "updates",
			Tone:        "cyan",
		},
		{
			ID:          "auto-update-run",
			Label:       "Запустить автообновление",
			Description: "Выполнить selector-aware auto-update сейчас",
			Command:     []string{"/opt/bin/vless-go-auto-update", "run"},
			Timeout:     120 * time.Second,
			Group:       "updates",
			Tone:        "cyan",
		},
		{
			ID:          "recover-status",
			Label:       "Recovery status",
			Description: "Статус тихой hourly recovery-проверки",
			Command:     []string{"/opt/bin/xray-go", "recover", "status"},
			Timeout:     15 * time.Second,
			Group:       "watchdog",
			Tone:        "secondary",
		},
		{
			ID:          "recover-check",
			Label:       "Recovery check",
			Description: "Проверить здоровье без recovery-действий",
			Command:     []string{"/opt/bin/xray-go", "recover", "check"},
			Timeout:     30 * time.Second,
			Group:       "watchdog",
			Tone:        "secondary",
		},
		{
			ID:          "recover-run",
			Label:       "Recover now",
			Description: "Запустить self-healing цепочку сейчас",
			Command:     []string{"/opt/bin/xray-go", "recover"},
			Timeout:     120 * time.Second,
			Group:       "watchdog",
			Tone:        "amber",
		},
		{
			ID:          "recover-enable-hourly",
			Label:       "Enable hourly recovery",
			Description: "Включить ежечасную тихую проверку",
			Command:     []string{"/opt/bin/xray-go", "recover", "enable-hourly"},
			Timeout:     30 * time.Second,
			Group:       "watchdog",
			Tone:        "cyan",
		},
		{
			ID:          "recover-disable-hourly",
			Label:       "Disable hourly recovery",
			Description: "Отключить ежечасную recovery-проверку",
			Command:     []string{"/opt/bin/xray-go", "recover", "disable-hourly"},
			Timeout:     30 * time.Second,
			Group:       "watchdog",
			Tone:        "secondary",
		},
		{
			ID:          "restart-xray",
			Label:       "Перезапустить Xray",
			Description: "Перезапустить S24xray",
			Command:     []string{"/opt/etc/init.d/S24xray", "restart"},
			Timeout:     30 * time.Second,
			Group:       "maintenance",
			Tone:        "secondary",
		},
		{
			ID:          "restart-watchdog",
			Label:       "Перезапустить watchdog",
			Description: "Перезапустить S26vless-go-watchdog",
			Command:     []string{"/opt/etc/init.d/S26vless-go-watchdog", "restart"},
			Timeout:     30 * time.Second,
			Group:       "maintenance",
			Tone:        "secondary",
		},
		{
			ID:          "history",
			Label:       "История переключений",
			Description: "Показать историю через xray-go",
			Command:     []string{"/opt/bin/xray-go", "history"},
			Timeout:     20 * time.Second,
			Group:       "logs",
			Tone:        "secondary",
		},
		{
			ID:          "recovery-log",
			Label:       "Recovery log",
			Description: "Последние строки recovery log",
			Command:     []string{"/bin/sh", "-c", "tail -n 80 /opt/var/log/vless-go-recover.log 2>/dev/null || true"},
			Timeout:     20 * time.Second,
			Group:       "logs",
			Tone:        "secondary",
		},
		{
			ID:          "watchdog-log",
			Label:       "Watchdog log",
			Description: "Последние строки watchdog log",
			Command:     []string{"/bin/sh", "-c", "tail -n 80 /opt/var/log/vless-go-watchdog.log 2>/dev/null || true"},
			Timeout:     20 * time.Second,
			Group:       "logs",
			Tone:        "secondary",
		},
		{
			ID:          "cleanup-dry-run",
			Label:       "Проверка очистки",
			Description: "Предпросмотр безопасной очистки",
			Command:     []string{"/opt/bin/vless-go-cleanup", "--dry-run"},
			Timeout:     30 * time.Second,
			Group:       "maintenance",
			Tone:        "secondary",
		},
	}
}
