#!/bin/sh
set -e

# xray-go-manifest - small manifest helper for Keenetic Xray Go direct-install v2.
#
# The manifest intentionally uses a simple KEY="value" format so it can be
# read safely by shell helpers, doctor, web UI and future direct-install code.
# It must never store raw VLESS links, subscription URLs, tokens or secrets.

MANIFEST_FILE="${XRAY_GO_MANIFEST:-/opt/etc/xray/xray-go.manifest}"
MANIFEST_DIR="$(dirname "$MANIFEST_FILE")"

usage() {
    cat <<'EOF'
xray-go-manifest - helper for /opt/etc/xray/xray-go.manifest

Usage:
  xray-go-manifest show
  xray-go-manifest summary
  xray-go-manifest init [options]
  xray-go-manifest set KEY VALUE
  xray-go-manifest touch-update
  xray-go-manifest path
  xray-go-manifest help

init options:
  --install-mode VALUE     direct|opkg|unknown
  --edition VALUE          full|minimal|unknown
  --version VALUE          project/installer version
  --arch VALUE             router architecture
  --channel VALUE          release channel or branch
  --source VALUE           source tag/commit/url label
  --binary-path VALUE      installed main binary path
  --binary-sha256 VALUE    sha256 of installed main binary
  --modules VALUE          comma-separated enabled modules

Examples:
  xray-go-manifest init --install-mode direct --edition full --version 0.2.0 --arch mipsle
  xray-go-manifest set LAST_UPDATE_AT "2026-06-07T12:00:00Z"
  xray-go-manifest summary
EOF
}

now_utc() {
    date -u '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || date '+%Y-%m-%dT%H:%M:%S%z'
}

escape_value() {
    # Keep values single-line and shell-readable.
    # Backslash and double quote are escaped; CR is dropped.
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\r//g; s/\n/ /g'
}

valid_key() {
    case "$1" in
        ''|*[!A-Za-z0-9_]*) return 1 ;;
        [0-9]*) return 1 ;;
        *) return 0 ;;
    esac
}

safe_value_line() {
    key="$1"
    value="$2"
    valid_key "$key" || { echo "ERROR: invalid manifest key: $key" >&2; exit 2; }
    printf '%s="%s"\n' "$key" "$(escape_value "$value")"
}

ensure_manifest_dir() {
    mkdir -p "$MANIFEST_DIR"
}

manifest_exists() {
    [ -s "$MANIFEST_FILE" ]
}

show_manifest() {
    if manifest_exists; then
        cat "$MANIFEST_FILE"
    else
        echo "Manifest not found: $MANIFEST_FILE" >&2
        return 1
    fi
}

get_value() {
    key="$1"
    sed -n 's/^'"$key"'="\(.*\)"$/\1/p' "$MANIFEST_FILE" 2>/dev/null | tail -n 1
}

summary_manifest() {
    if ! manifest_exists; then
        echo "Manifest: not found ($MANIFEST_FILE)"
        return 1
    fi

    echo "Manifest: $MANIFEST_FILE"
    echo "Install mode: $(get_value INSTALL_MODE)"
    echo "Edition: $(get_value EDITION)"
    echo "Version: $(get_value VERSION)"
    echo "Architecture: $(get_value ARCH)"
    echo "Channel: $(get_value CHANNEL)"
    echo "Source: $(get_value SOURCE)"
    echo "Binary: $(get_value BINARY_PATH)"
    echo "Binary sha256: $(get_value BINARY_SHA256)"
    echo "Modules: $(get_value MODULES)"
    echo "Installed at: $(get_value INSTALLED_AT)"
    echo "Last update at: $(get_value LAST_UPDATE_AT)"
}

write_init_manifest() {
    install_mode="unknown"
    edition="unknown"
    version="unknown"
    arch="unknown"
    channel="unknown"
    source="unknown"
    binary_path=""
    binary_sha256=""
    modules=""

    while [ "$#" -gt 0 ]; do
        case "$1" in
            --install-mode) install_mode="${2:-}"; shift 2 ;;
            --edition) edition="${2:-}"; shift 2 ;;
            --version) version="${2:-}"; shift 2 ;;
            --arch) arch="${2:-}"; shift 2 ;;
            --channel) channel="${2:-}"; shift 2 ;;
            --source) source="${2:-}"; shift 2 ;;
            --binary-path) binary_path="${2:-}"; shift 2 ;;
            --binary-sha256) binary_sha256="${2:-}"; shift 2 ;;
            --modules) modules="${2:-}"; shift 2 ;;
            -h|--help|help) usage; exit 0 ;;
            *) echo "ERROR: unknown init option: $1" >&2; usage >&2; exit 2 ;;
        esac
    done

    case "$install_mode" in direct|opkg|unknown) ;; *) echo "ERROR: unsupported install mode: $install_mode" >&2; exit 2 ;; esac
    case "$edition" in full|minimal|unknown) ;; *) echo "ERROR: unsupported edition: $edition" >&2; exit 2 ;; esac

    ensure_manifest_dir
    tmp="${MANIFEST_FILE}.$$"
    {
        echo '# Keenetic Xray Go manifest'
        echo '# Generated by xray-go-manifest. Do not store secrets here.'
        safe_value_line SCHEMA "xray-go.manifest.v1"
        safe_value_line INSTALL_MODE "$install_mode"
        safe_value_line EDITION "$edition"
        safe_value_line VERSION "$version"
        safe_value_line ARCH "$arch"
        safe_value_line CHANNEL "$channel"
        safe_value_line SOURCE "$source"
        safe_value_line BINARY_PATH "$binary_path"
        safe_value_line BINARY_SHA256 "$binary_sha256"
        safe_value_line MODULES "$modules"
        safe_value_line INSTALLED_AT "$(now_utc)"
        safe_value_line LAST_UPDATE_AT ""
    } >"$tmp"
    chmod 600 "$tmp" 2>/dev/null || true
    mv "$tmp" "$MANIFEST_FILE"
    echo "Manifest written: $MANIFEST_FILE"
}

set_key() {
    key="${1:-}"
    value="${2:-}"
    [ -n "$key" ] || { echo "ERROR: set requires KEY VALUE" >&2; exit 2; }
    [ "$#" -ge 2 ] || { echo "ERROR: set requires KEY VALUE" >&2; exit 2; }
    valid_key "$key" || { echo "ERROR: invalid manifest key: $key" >&2; exit 2; }
    ensure_manifest_dir

    tmp="${MANIFEST_FILE}.$$"
    if manifest_exists; then
        grep -v '^'"$key"'=' "$MANIFEST_FILE" >"$tmp" || true
    else
        {
            echo '# Keenetic Xray Go manifest'
            echo '# Generated by xray-go-manifest. Do not store secrets here.'
            safe_value_line SCHEMA "xray-go.manifest.v1"
        } >"$tmp"
    fi
    safe_value_line "$key" "$value" >>"$tmp"
    chmod 600 "$tmp" 2>/dev/null || true
    mv "$tmp" "$MANIFEST_FILE"
    echo "Manifest updated: $key"
}

case "${1:-help}" in
    show|cat)
        show_manifest
        ;;
    summary|status)
        summary_manifest
        ;;
    init|write)
        shift
        write_init_manifest "$@"
        ;;
    set)
        shift
        set_key "$@"
        ;;
    touch-update)
        set_key LAST_UPDATE_AT "$(now_utc)"
        ;;
    path)
        echo "$MANIFEST_FILE"
        ;;
    help|-h|--help|"")
        usage
        ;;
    *)
        echo "ERROR: unknown command: $1" >&2
        usage >&2
        exit 2
        ;;
esac
