name: Control server CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - cmd/xray-go-control-server/**
      - .github/workflows/control-server-ci.yml
  push:
    branches:
      - main
      - feature-router-groups
    paths:
      - cmd/xray-go-control-server/**
      - .github/workflows/control-server-ci.yml

permissions:
  contents: read

jobs:
  build-control-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Show formatting differences
        continue-on-error: true
        run: |
          gofmt -l cmd/xray-go-control-server

      - name: Build control server amd64
        run: |
          CGO_ENABLED=0 GO111MODULE=off GOOS=linux GOARCH=amd64 \
            go build -trimpath -o /tmp/xray-go-control-server ./cmd/xray-go-control-server

      - name: Build control server arm64
        run: |
          CGO_ENABLED=0 GO111MODULE=off GOOS=linux GOARCH=arm64 \
            go build -trimpath -o /tmp/xray-go-control-server-arm64 ./cmd/xray-go-control-server
